src/Security/Entity/User.php
<?php

namespace App\Security\Entity;

use App\Band\Entity\ApplicationComment;
use App\Band\Entity\ApplicationFavorite;
use App\Band\Entity\ApplicationHistory;
use App\Band\Entity\ApplicationScore;
use App\Band\Entity\FinalScore;
use App\Inventory\Entity\Item;
use App\Inventory\Entity\Log;
use App\Volunteer\Entity\ShiftArea;
use App\Volunteer\Entity\Volunteer;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Security\Repository\UserRepository")
 * @UniqueEntity(
 *     fields={"email"},
 *     message="email.duplicate"
 * )
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface {
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email
     * @Assert\NotBlank
     */
    private ?string $email = null;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $name = null;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private string $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $activation_token = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $registered_at = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $activationEmailSentAt = null;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTimeInterface $activated_at = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $last_login = null;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $password_reset = null;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTimeInterface $password_reset_timeout = null;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $force_reset = null;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private ?string $lang = null;

    /**
     * @ORM\OneToOne(targetEntity="App\Volunteer\Entity\Volunteer", mappedBy="user", cascade={"persist", "remove"})
     */
    private ?Volunteer $volunteer = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Volunteer\Entity\ShiftArea", mappedBy="supervisor")
     */
    private Collection $supervisingAreas;

    /**
     * @ORM\OneToMany(targetEntity="App\Security\Entity\PermissionInheritance", mappedBy="user")
     */
    private Collection $permissionInheritances;

    /**
     * @ORM\OneToMany(targetEntity="App\Band\Entity\ApplicationHistory", mappedBy="user", orphanRemoval=true)
     */
    private Collection $bandApplicationHistories;

    /**
     * @ORM\OneToMany(targetEntity="App\Band\Entity\ApplicationScore", mappedBy="user", orphanRemoval=true)
     */
    private Collection $bandApplicationScores;

    /**
     * @ORM\OneToMany(targetEntity="App\Band\Entity\ApplicationFavorite", mappedBy="user", orphanRemoval=true)
     */
    private Collection $bandApplicationFavorites;

    /**
     * @ORM\OneToMany(targetEntity="App\Band\Entity\ApplicationComment", mappedBy="author", orphanRemoval=true)
     */
    private Collection $bandApplicationComments;

    /**
     * @ORM\OneToMany(targetEntity="App\Band\Entity\FinalScore", mappedBy="user", orphanRemoval=true)
     */
    private Collection $bandFinalScores;

    /**
     * @ORM\OneToMany(targetEntity="App\Inventory\Entity\Item", mappedBy="borrowedBy")
     */
    private Collection $inventoryItems;

    public function __construct() {
        $this->supervisingAreas = new ArrayCollection();
        $this->permissionInheritances = new ArrayCollection();
        $this->bandApplicationHistories = new ArrayCollection();
        $this->bandApplicationScores = new ArrayCollection();
        $this->bandApplicationFavorites = new ArrayCollection();
        $this->bandApplicationComments = new ArrayCollection();
        $this->bandFinalScores = new ArrayCollection();
        $this->inventoryItems = new ArrayCollection();
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getEmail(): ?string {
        return $this->email;
    }

    public function setEmail(string $email): self {
        $this->email = $email;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getUserIdentifier(): string {
        return $this->email;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string {
        return $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string {
        return $this->password;
    }

    public function setPassword(string $password): self {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt(): ?string {
        // not needed when using the "bcrypt" algorithm in security.yaml
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials() {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string {
        return $this->name;
    }

    public function setName(?string $name): self {
        $this->name = $name;

        return $this;
    }

    public function getDisplayName(): string {
        if ($this->name != null)
            return $this->name;
        return $this->email;
    }

    public function getActivationToken(): ?string {
        return $this->activation_token;
    }

    public function setActivationToken(string $activation_token): self {
        $this->activation_token = $activation_token;

        return $this;
    }

    public function getRegisteredAt(): ?DateTimeInterface {
        return $this->registered_at;
    }

    public function setRegisteredAt(DateTimeInterface $registered_at): self {
        $this->registered_at = $registered_at;

        return $this;
    }

    public function getActivationEmailSentAt(): ?DateTimeInterface {
        return $this->activationEmailSentAt;
    }

    public function setActivationEmailSentAt(DateTimeInterface $activationEmailSentAt): self {
        $this->activationEmailSentAt = $activationEmailSentAt;

        return $this;
    }

    public function getActivatedAt(): ?DateTimeInterface {
        return $this->activated_at;
    }

    public function setActivatedAt(?DateTimeInterface $activated_at): self {
        $this->activated_at = $activated_at;

        return $this;
    }

    public function getLastLogin(): ?DateTimeInterface {
        return $this->last_login;
    }

    public function setLastLogin(DateTimeInterface $last_login): self {
        $this->last_login = $last_login;

        return $this;
    }

    public function getPasswordReset(): ?string {
        return $this->password_reset;
    }

    public function setPasswordReset(?string $password_reset): self {
        $this->password_reset = $password_reset;

        return $this;
    }

    public function getPasswordResetTimeout(): ?DateTimeInterface {
        return $this->password_reset_timeout;
    }

    public function setPasswordResetTimeout(?DateTimeInterface $password_reset_timeout): self {
        $this->password_reset_timeout = $password_reset_timeout;

        return $this;
    }

    public function getForceReset(): ?bool {
        return $this->force_reset;
    }

    public function setForceReset(bool $force_reset): self {
        $this->force_reset = $force_reset;

        return $this;
    }

    public function getLang(): ?string {
        return $this->lang;
    }

    public function setLang(string $lang): self {
        $this->lang = $lang;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array {
        return ['ROLE_USER'];
    }

    public function getVolunteer(): ?Volunteer {
        return $this->volunteer;
    }

    public function setVolunteer(Volunteer $volunteer): self {
        $this->volunteer = $volunteer;

        // set the owning side of the relation if necessary
        if ($this !== $volunteer->getUser()) {
            $volunteer->setUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|ShiftArea[]
     */
    public function getSupervisingAreas(): Collection {
        return $this->supervisingAreas;
    }

    public function addSupervisingArea(ShiftArea $supervisingArea): self {
        if (!$this->supervisingAreas->contains($supervisingArea)) {
            $this->supervisingAreas[] = $supervisingArea;
            $supervisingArea->setSupervisor($this);
        }

        return $this;
    }

    public function removeSupervisingArea(ShiftArea $supervisingArea): self {
        if ($this->supervisingAreas->contains($supervisingArea)) {
            $this->supervisingAreas->removeElement($supervisingArea);
            // set the owning side to null (unless already changed)
            if ($supervisingArea->getSupervisor() === $this) {
                $supervisingArea->setSupervisor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PermissionInheritance[]
     */
    public function getPermissionInheritances(): Collection {
        return $this->permissionInheritances;
    }

src/Security/Controller/AccountController.php
<?php

namespace App\Security\Controller;

use App\Security\Entity\User;
use App\Security\Form\AccountForm;
use App\System\Application\ConfigService;
use App\System\Application\MailService;
use App\System\Application\TokenGeneratorService;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route(path: '/account')]
class AccountController extends AbstractController {
    #[Route(path: '/', name: 'app_account')]
    public function account(Request                     $request,
                            UserPasswordHasherInterface $passwordHasher,
                            TranslatorInterface         $trans,
                            TokenGeneratorService       $token,
                            EntityManagerInterface      $doctrine,
                            MailService                 $mail) {
        // force the user to log in if they used remember_me
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        /** @var User $user */
        $user = $this->getUser();
        $oldemail = $user->getEmail();

        $form = $this->createForm(AccountForm::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $password = $form->get('password')->getData();
            if (!empty($password)) {
                if ($password == $form->get('passwordConfirm')->getData()) {
                    $this->addFlash('success', $trans->trans('password.reset.success'));
                    $user->setPassword($passwordHasher->hashPassword($user, $password));
                } else $form->get('passwordConfirm')->addError(new FormError($trans->trans('password.nomatch')));
            }

            if ($oldemail != $user->getEmail()) {
                $user->setActivationToken($token->generateToken(16));
                $user->setActivatedAt(null);
                $user->setActivationEmailSentAt(new DateTimeImmutable());
                $mail->sendChangeaddressEmail($user);
            }

            $doctrine->persist($user);
            $doctrine->flush();
        }

        return $this->render('security/account.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route(path: '/reset', name: 'app_reset')]
    public function reset(Request               $request,
                          TranslatorInterface   $trans,
                          TokenGeneratorService $tokenGenerator,
                          MailService           $mail): Response {

        $form = $this->createFormBuilder()
            ->add('email', EmailType::class, [
                'label' => 'password.reset.email',
                'invalid_message' => 'email.invalid',
                'required' => true,
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'password.reset.label'
            ])
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $doctrine = $this->getDoctrine()->getManager();
            /** @var $user User */
            $user = $doctrine->getRepository('App\Security\Entity\User')->findOneBy([
                'email' => $form->get('email')->getData()
            ]);
            $this->addFlash('success', $trans->trans('password.reset.sent'));
            if ($user !== null) {
                $token = $tokenGenerator->generateToken(32);
                $token_hash = password_hash($token, PASSWORD_BCRYPT, array('cost' => ConfigService::PASSWORD_HASH_STRENGTH));
                $user->setPasswordReset($token_hash);
                $user->setPasswordResetTimeout(new DateTimeImmutable('+1 hour'));
                $doctrine->persist($user);
                $doctrine->flush();

                $mail->sendResetEmail($user, $token);
            }
            return $this->redirectToRoute('index');
        }
        return $this->render('security/reset.html.twig', [
            'form' => $form->createView(),
            'reset' => false
        ]);

    }

    /**
     * Allows a user to reset their password.
     *
     * @param int $userid user to reset
     * @param string $token token for verification
     */
    #[Route(path: '/reset/{userid}/{token}', name: 'app_reset_new')]
    public function resetNew(int                         $userid,
                             string                      $token,
                             Request                     $request,
                             TranslatorInterface         $trans,
                             UserPasswordHasherInterface $passwordHasher): Response {

        $doctrine = $this->getDoctrine()->getManager();
        /** @var $user User */
        $user = $doctrine->getRepository('App\Security\Entity\User')->find($userid);
        if ($user !== null) {
            if ($user->getPasswordResetTimeout() === null || $user->getPasswordResetTimeout()->diff(new DateTimeImmutable())->invert === 0) {
                $this->addFlash('danger', $trans->trans('password.reset.timeout'));
                return $this->redirectToRoute('index');
            }

            if (!password_verify($token, $user->getPasswordReset())) {
                $this->addFlash('danger', $trans->trans('password.reset.invalid'));
                return $this->redirectToRoute('index');
            }

            $form = $this->createFormBuilder()
                ->add('password', PasswordType::class, [
                    'label' => 'password.new.label',
                    'invalid_message' => 'password.weak',
                    'constraints' => [
                        new Length([
                            'min' => ConfigService::PASSWORD_MIN_LENGTH,
                            'max' => ConfigService::PASSWORD_MAX_LENGTH,
                        ])
                    ]
                ])
                ->add('passwordConfirm', PasswordType::class, [
                    'label' => 'password.new.confirm'
                ])
                ->add('submit', SubmitType::class, [
                    'label' => 'send'
                ])
                ->getForm();
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $pwPlain = $form->get('password')->getData();
                $pwConfi = $form->get('passwordConfirm')->getData();

                if ($pwPlain === $pwConfi) {
                    $user->setPassword($passwordHasher->hashPassword($user, $pwPlain));
                    $user->setPasswordReset(null);
                    $user->setPasswordResetTimeout(null);
                    $doctrine->persist($user);
                    $doctrine->flush();
                    $this->addFlash('success', $trans->trans('password.reset.success'));
                    return $this->redirectToRoute('app_login');
                }

                $form->get('passwordConfirm')->addError(new FormError($trans->trans('password.nomatch')));
            }

            return $this->render('security/reset.html.twig', [
                'form' => $form->createView(),
                'reset' => true
            ]);
        }

        $this->addFlash('danger', $trans->trans('password.reset.invalid'));
        return $this->redirectToRoute('index');
    }
}

templates/security/admin/groups.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}Gruppen{% endblock %}

{% block body %}
    <p class="fs-3 m-0">Admin Bereich: Gruppen</p>
    <a href="{{ path('admin_users') }}">Benutzer</a>
    <div id="vue-groups">
        <groups-table def="{{ groups|json_encode|escape('html_attr') }}"></groups-table>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('admin/groups') }}
{% endblock %}

templates/security/admin/index.html.twig
{% extends 'base_sidebar.html.twig' %}
{% import 'buttons.html.twig' as buttons %}

{% block title %}Backstage Admin{% endblock %}

{% block body %}
    <p class="fs-3 m-0">Admin Bereich</p>
    <div class="row mt-3">
        {% if is_granted('admin.users') %}
            <div class="col mx-auto">
                {{ buttons.link(path('admin_users'), 'fa-user', 'Benutzer') }}
            </div>
        {% endif %}
        {% if is_granted('admin.groups') %}
            <div class="col mx-auto">
                {{ buttons.link(path('admin_groups'), 'fa-users', 'Gruppen') }}
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/security/admin/user.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}{{ user.name }}{% endblock %}

{% block body %}
    <p class="fs-3 m-0">Admin Bereich: {{ user.displayName }}</p>
    <a href="{{ path('admin_users') }}">Benutzer</a>
    <a href="{{ path('admin_groups') }}">Gruppen</a>

    <div class="row mt-3">
        <div class="col-12 col-md-8 p-2">
            <div class="card">
                <div class="card-header">
                    <strong>{{ user.name ? user.name : user.email }}</strong>
                    {% if user.id != app.user.id %}
                        <a href="{{ path('index', {'_switch_user': user.email}) }}"><i class="fas fa-user-secret py-1 float-end"></i></a>
                    {% endif %}
                </div>
                <table class="table mb-0">
                    <tr>
                        <th scope="row" class="border-top-0">ID:</th>
                        <td class="border-top-0">{{ user.id }}</td>
                    </tr>
                    <tr>
                        <th scope="row">E-Mail:</th>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Name:</th>
                        <td>{{ user.name ?? '-' }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Registriert:</th>
                        <td>{{ user.registeredAt|date('d.m.Y H:i') }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Aktiviert:</th>
                        <td>{{ user.activatedAt is null ? 'nein' : user.activatedAt|date('d.m.Y H:i') }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Zuletzt aktiv:</th>
                        <td>{{ user.lastLogin|date('d.m.Y H:i') }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Sprache:</th>
                        <td>{{ user.lang }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-12 col-md-4 p-2" id="vue-inheritances">
            <inheritance-list user="{{ user.id }}" def-inh="{{ inheritances|json_encode|escape('html_attr') }}" def-groups="{{ groups|json_encode|escape('html_attr') }}"></inheritance-list>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('admin/users') }}
{% endblock %}

templates/security/admin/users.html.twig
{% extends 'base_sidebar.html.twig' %}

{% block title %}Benutzer{% endblock %}

{% block body %}
    <p class="fs-3 m-0">Admin Bereich: Benutzer</p>
    <a href="{{ path('admin_groups') }}">Gruppen</a>
    <div class="card mt-3">
        <div class="card-header">
            {{ form_start(form) }}
            <div class="input-group">
                <span class="my-auto me-2">Alle Nutzer</span>
                {{ form_widget(form.email, {'attr': {'class': 'ms-auto me-2', 'style': 'max-width: 250px; min-width: 180px', 'placeholder': 'email'}}) }}
                {{ form_widget(form.search, {'attr': {'class': 'btn-outline-secondary'}}) }}
            </div>
            {{ form_end(form) }}
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm">
                    <thead>
                    <tr>
                        <th>E-Mail</th>
                        <th>Name</th>
                        <th colspan="2">Aktiviert</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.email }}</td>
                            <td>{{ user.name }}</td>
                            <td>{{ user.activated_at is not null ? user.activated_at|date('d.m.Y') : 'Nein' }}</td>
                            <td>
                                <a href="{{ path('admin_user', {'user': user.id}) }}"><i class="fas fa-pen"></i></a>
                                {% if user.id != app.user.id %}
                                    <a href="{{ path('index', {'_switch_user': user.email}) }}"><i class="fas fa-user-secret ms-2"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% if pageCount > 1 %}
            <div class="card-footer">
                <nav aria-label="User navigation">
                    <ul class="pagination mb-0">
                        {% if page > 1 %}
                            <li class="page-item">
                                <a class="btn btn-link page-link" href="{{ path('admin_users', {'page': page - 1}) }}" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                        {% endif %}
                        {% for i in 1..pageCount %}
                            <li class="page-item {{ i == page ? 'active' }}">
                                <a class="btn btn-link page-link" href="{{ path('admin_users', {'page': i}) }}">{{ i }}</a>
                            </li>
                        {% endfor %}
                        {% if page < pageCount %}
                            <li class="page-item">
                                <a class="btn btn-link page-link" href="{{ path('admin_users', {'page': page + 1}) }}" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% endif %}
    </div>
{% endblock %}